openapi: 3.1.0
info:
  title: Klachten Memo Samenvatter
  version: 1.1.0
  description: |
    Deze API verwerkt vrij ingevoerde klachtenmemo's en vat deze samen in een vaste structuur:
    (1) Onderzoek van de klacht;
    (2) Herstel en uitvoering;
    (3) Evaluatie en verbetermaatregelen;
    (4) Tijdlijn van gebeurtenissen;
    (5) Betrokken personen of afdelingen;
    (6) Juridische implicaties.

    De API produceert zakelijke, beknopte samenvattingen per onderdeel. Informatie die ontbreekt wordt expliciet benoemd.
servers:
  - url: https://fastapi-gpt-api-1.onrender.com
paths:
  /verwerk_memo:
    post:
      summary: Verwerk een klachtenmemo en vat samen in 6 onderdelen
      operationId: verwerkMemo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tekst:
                  type: string
      responses:
        '200':
          description: Samenvatting gegenereerd
          content:
            application/json:
              schema:
                type: object
                properties:
                  onderzoek:
                    type: string
                  herstel:
                    type: string
                  evaluatie:
                    type: string
                  tijdlijn:
                    type: string
                  betrokkenen:
                    type: string
                  juridisch:
                    type: string
