openapi: 3.0.0
info:
  title: Bedrijfs API
  version: 1.0.0
  description: API om klantgegevens op te halen en offertes aan te maken.
servers:
  - url: https://fastapi-gpt-api-1.onrender.com
paths:
  /klanten/{klant_id}:
    get:
      summary: Haal klantgegevens op via klant-ID
      operationId: getKlant
      parameters:
        - name: klant_id
          in: path
          required: true
          description: Unieke klant-ID
          schema:
            type: string
      responses:
        '200':
          description: Succesvolle response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  naam:
                    type: string
                  email:
                    type: string
                  telefoon:
                    type: string

  /offertes:
    post:
      summary: Maak een nieuwe offerte aan
      operationId: createOfferte
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                klantId:
                  type: string
                beschrijving:
                  type: string
                bedrag:
                  type: number
                  format: float
      responses:
        '201':
          description: Offerte succesvol aangemaakt
          content:
            application/json:
              schema:
                type: object
                properties:
                  offerteId:
                    type: string
                  status:
                    type: string
