openapi: 3.1.0
info:
  title: Klachten Memo Samenvatter
  version: 1.0.0
  description: API om vrije klachtenmemo's samen te vatten in vaste rapportagestructuur.
servers:
  - url: https://fastapi-gpt-api-1.onrender.com
paths:
  /verwerk_memo:
    post:
      summary: Verwerk een klachtenmemo en vat samen in 3 onderdelen
      operationId: verwerkMemo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tekst:
                  type: string
      responses:
        '200':
          description: Samenvatting gegenereerd
          content:
            application/json:
              schema:
                type: object
                properties:
                  onderzoek:
                    type: string
                  herstel:
                    type: string
                  evaluatie:
                    type: string
